import type { InvoiceData } from '../types/invoice'

export function getMockData(corporate = false): InvoiceData {
  return corporate ? getMockCorporateData() : getMockPersonalData()
}

function getMockPersonalData(): InvoiceData {
  return {
    orderId: '735179',
    sequence: 'AA01455969',
    marketplaceOrderId: '735179',
    marketplaceServicesEndpoint:
      'http://oms.vtexinternal.com.br/api/oms?an=chanel',
    sellerOrderId: '00-v735179chanel-01',
    origin: 'Marketplace',
    affiliateId: 'CHN',
    salesChannel: '1',
    merchantName: 'chanel',
    status: 'handling',
    workflowIsInError: false,
    statusDescription: 'Préparation de la commande',
    value: 2700,
    creationDate: '2021-09-14T14:34:00.000+00:00',
    lastChange: '2021-09-14T14:34:00.000+00:00',
    orderGroup: '735179',
    followUpEmail: 'service@chanel.com',
    lastMessage: 'Votre paiement a été approuvé',
    hostname: 'chanel',
    isCompleted: true,
    roundingError: 0,
    orderFormId: 'chanel-735179',
    allowCancellation: true,
    allowEdition: false,
    isCheckedIn: false,
    authorizedDate: '2021-09-14T14:34:00.000+00:00',
    invoicedDate: '2021-09-14T14:34:00.000+00:00',
    cancelReason: '',
    checkedInPickupPointId: '',
    clientProfileData: {
      id: 'clientProfile_735179',
      email: 'leana.belkhiri@email.com',
      firstName: 'Léana',
      lastName: 'BELKHIRI',
      documentType: 'siret',
      document: '542052766',
      phone: '+33 (0) 1 44 50 66 00',
      corporateName: null,
      tradeName: null,
      corporateDocument: null,
      stateInscription: null,
      corporatePhone: null,
      isCorporate: false,
      userProfileId: 'user-735179',
      userProfileVersion: 'v1',
      customerClass: null,
      customerCode: 'BELKHIRI-735179',
    },
    shippingData: {
      id: 'shippingData',
      address: {
        addressType: 'residential',
        receiverName: 'Madame Léana BELKHIRI',
        addressId: '66000',
        versionId: 'v1',
        entityId: 'entity-735179',
        postalCode: '66000',
        city: 'PERPIGNAN',
        state: '',
        country: 'FRA',
        street: '22 ESPACE MEDITERRANEE',
        number: '',
        neighborhood: '',
        complement: '',
        reference: '',
        geoCoordinates: [],
      },
      logisticsInfo: [
        {
          itemIndex: 0,
          selectedSla: 'Standard',
          lockTTL: '10d',
          price: 0,
          listPrice: 0,
          sellingPrice: 0,
          deliveryWindow: null,
          deliveryCompany: 'CHANEL Livraison',
          shippingEstimate: '3bd',
          shippingEstimateDate: '2021-09-17T14:34:00.000+00:00',
          slas: [
            {
              id: 'Standard',
              name: 'Standard',
              shippingEstimate: '3bd',
              deliveryWindow: null,
              price: 0,
              deliveryChannel: 'delivery',
              pickupStoreInfo: {
                additionalInfo: null,
                address: null,
                dockId: null,
                friendlyName: null,
                isPickupStore: false,
              },
              polygonName: '',
              lockTTL: '10d',
              pickupPointId: null,
              transitTime: '3d',
              pickupDistance: 0,
            },
          ],
          shipsTo: ['FRA'],
          deliveryIds: [
            {
              courierId: 'chanel_courier',
              courierName: 'CHANEL Express',
              dockId: 'dock_chanel',
              quantity: 1,
              warehouseId: 'warehouse_paris',
              accountCarrierName: 'chanel',
              kitItemDetails: [],
            },
          ],
          deliveryChannels: [
            {
              id: 'delivery',
              stockBalance: 0,
            },
          ],
          deliveryChannel: 'delivery',
          pickupStoreInfo: {
            additionalInfo: null,
            address: null,
            dockId: null,
            friendlyName: null,
            isPickupStore: false,
          },
          addressId: '66000',
          versionId: null,
          entityId: null,
          polygonName: '',
          pickupPointId: null,
          transitTime: '3d',
        },
      ],
      trackingHints: [],
      selectedAddresses: [
        {
          addressType: 'residential',
          receiverName: 'Madame Léana BELKHIRI',
          addressId: '66000',
          versionId: 'v1',
          entityId: 'entity-735179',
          postalCode: '66000',
          city: 'PERPIGNAN',
          state: '',
          country: 'FRA',
          street: '22 ESPACE MEDITERRANEE',
          number: '',
          neighborhood: '',
          complement: '',
          reference: '',
          geoCoordinates: [],
        },
      ],
      contactInformation: [
        {
          id: '0',
          email: 'leana.belkhiri@email.com',
          firstName: 'Léana',
          lastName: 'BELKHIRI',
          phone: '+33 (0) 1 44 50 66 00',
          document: '542052766',
          documentType: 'siret',
          entityId: 'entity-735179',
          versionId: 'v1',
        },
      ],
    },
    items: [
      {
        uniqueId: 'AP0250Y01480C3906-01',
        id: '1',
        productId: '1',
        ean: '',
        lockId: '00-735179-01',
        itemAttachment: {
          content: {},
          name: null,
        },
        attachments: [],
        quantity: 1,
        seller: '1',
        name: 'Sac Caviar & Or Noir',
        refId: 'AP0250Y01480C3906',
        price: 2700,
        listPrice: 2700,
        manualPrice: null,
        priceTags: [],
        imageUrl: '',
        detailUrl: '/sac-caviar-or-noir/p',
        components: [],
        bundleItems: [],
        params: [],
        offerings: [],
        attachmentOfferings: [],
        sellerSku: 'AP0250Y01480C3906',
        priceValidUntil: '2022-09-14T14:34:00.000+00:00',
        commission: 0,
        tax: 450,
        preSaleDate: null,
        additionalInfo: {
          brandName: 'CHANEL',
          brandId: '1',
          categoriesIds: '/1/',
          categories: [
            {
              id: 1,
              name: 'Maroquinerie',
            },
          ],
          productClusterId: '',
          commercialConditionId: '1',
          dimension: {
            cubicweight: 1,
            height: 0,
            length: 0,
            weight: 0,
            width: 0,
          },
          offeringInfo: null,
          offeringType: null,
          offeringTypeId: null,
        },
        measurementUnit: 'un',
        unitMultiplier: 1,
        sellingPrice: 2700,
        isGift: false,
        shippingPrice: null,
        rewardValue: 0,
        freightCommission: 0,
        priceDefinition: {
          sellingPrices: [
            {
              value: 2700,
              quantity: 1,
            },
          ],
          calculatedSellingPrice: 2700,
          total: 2700,
          reason: null,
        },
        taxCode: 'TVA_20',
        parentItemIndex: 0,
        parentAssemblyBinding: '',
        callCenterOperator: null,
        serialNumbers: null,
        assemblies: [],
        costPrice: 0,
      },
    ],
    marketplaceItems: [],
    sellers: [
      {
        id: '1',
        name: 'CHANEL',
        logo: 'https://chanel.com/logo.png',
        fulfillmentEndpoint:
          'http://fulfillment.vtexcommerce.com.br/api/fulfillment?an=chanel',
      },
    ],
    totals: [
      { id: 'Items', name: 'Total des Articles', value: 2700 },
      { id: 'Discounts', name: 'Total des Remises', value: 0 },
      { id: 'Shipping', name: 'Total de la Livraison', value: 0 },
      { id: 'Tax', name: 'Total de la TVA', value: 450 },
    ],
    clientPreferencesData: {
      locale: 'fr-FR',
      optinNewsLetter: false,
    },
    paymentData: {
      transactions: [
        {
          isActive: true,
          transactionId: 'TXN-735179',
          merchantName: 'chanel',
          payments: [
            {
              id: 'PAY-735179',
              paymentSystem: '1',
              paymentSystemName: 'Especes Euros',
              value: 2700,
              installments: 1,
              referenceValue: 2700,
              cardHolder: null,
              cardNumber: null,
              firstDigits: null,
              lastDigits: null,
              cvv2: null,
              expireMonth: null,
              expireYear: null,
              url: null,
              giftCardId: null,
              giftCardName: null,
              giftCardCaption: null,
              redemptionCode: null,
              group: 'cash',
              tid: null,
              dueDate: null,
              connectorResponses: {},
              giftCardProvider: null,
              giftCardAsDiscount: false,
              koinUrl: null,
              accountId: null,
              parentAccountId: null,
              bankIssuedInvoiceIdentificationNumber: null,
              bankIssuedInvoiceIdentificationNumberFormatted: null,
              bankIssuedInvoiceBarCodeNumber: null,
              bankIssuedInvoiceBarCodeType: null,
              billingAddress: null,
              paymentOrigin: null,
            },
          ],
        },
      ],
      giftCards: [],
    },
    storePreferencesData: {
      countryCode: 'FRA',
      currencyCode: 'EUR',
      currencyFormatInfo: {
        CurrencyDecimalDigits: 2,
        CurrencyDecimalSeparator: ',',
        CurrencyGroupSeparator: ' ',
        CurrencyGroupSize: 3,
        StartsWithCurrencySymbol: true,
      },
      currencyLocale: 1036,
      currencySymbol: '€',
      timeZone: 'Romance Standard Time',
    },
    taxData: {
      areTaxesDesignatedByMarketplace: true,
      taxInfoCollection: [
        {
          itemIndex: 0,
          sku: 'AP0250Y01480C3906',
          priceTags: [
            {
              identifier: 'tax-735179',
              isPercentual: true,
              name: 'TVA 20,00%',
              value: 450,
              rawValue: 0.2,
            },
          ],
        },
      ],
    },
    commercialConditionData: null,
    openTextField: null,
    invoiceData: {
      userPaymentInfo: null,
      address: null,
      invoiceSubject: null,
    },
    changesAttachment: {
      id: 'changeAttachment',
      changesData: [],
    },
    callCenterOperatorData: null,
    packageAttachment: {
      packages: [
        {
          items: [
            {
              itemIndex: 0,
              quantity: 1,
              price: 2700,
              description: 'Sac Caviar & Or Noir',
              unitMultiplier: 0,
            },
          ],
          courier: 'CHANEL Express',
          invoiceNumber: '735179',
          invoiceValue: 2700,
          invoiceUrl: 'https://chanel.com/invoices/735179.pdf',
          issuanceDate: '2021-09-14T14:34:00.000+00:00',
          trackingNumber: 'CHN-735179',
          invoiceKey: '',
          trackingUrl: '',
          embeddedInvoice: '',
          type: 'Input',
          courierStatus: null,
          cfop: '',
          restitutions: null,
          volumes: 1,
          EnableInferItems: false,
        },
      ],
    },
    ratesAndBenefitsData: {
      id: 'ratesAndBenefitsData',
      rateAndBenefitsIdentifiers: [],
    },
    marketingData: {
      id: 'marketingData',
      utmSource: '',
      utmPartner: '',
      utmMedium: '',
      utmCampaign: '',
      coupon: '',
      utmiCampaign: '',
      utmipage: '',
      utmiPart: '',
      marketingTags: [],
    },
    giftRegistryData: null,
    cancellationData: null,
    subscriptionData: null,
    customData: {
      customApps: [],
      customFields: [],
    },
    itemMetadata: {
      Items: [
        {
          Id: '1',
          Seller: '1',
          Name: 'Sac Caviar & Or Noir',
          SkuName: 'Sac Caviar & Or Noir',
          ProductId: '1',
          RefId: 'AP0250Y01480C3906',
          Ean: '',
          ImageUrl: '',
          DetailUrl: '/sac-caviar-or-noir/p',
          AssemblyOptions: [],
        },
      ],
    },
    marketplace: {
      baseURL: 'http://oms.vtexinternal.com.br/api/oms?an=chanel',
      isCertified: true,
      name: 'chanel',
    },
  }
}

function getMockCorporateData(): InvoiceData {
  const base = getMockPersonalData()

  return {
    ...base,
    orderId: '735180',
    sequence: 'AA01455970',
    clientProfileData: {
      id: 'clientProfile_735180',
      email: 'contact@lvmh.com',
      firstName: 'Jean-Pierre',
      lastName: 'MARTIN',
      documentType: 'siret',
      document: '542052766',
      phone: '+33 (0) 1 44 13 22 00',
      corporateName: 'LVMH MOËT HENNESSY LOUIS VUITTON',
      tradeName: 'LVMH',
      corporateDocument: '775 670 417 00012',
      stateInscription: null,
      corporatePhone: '+33 (0) 1 44 13 22 00',
      isCorporate: true,
      userProfileId: 'user-735180',
      userProfileVersion: 'v1',
      customerClass: 'corporate',
      customerCode: 'LVMH-735180',
    },
  }
}
